title: "Affiliates"
email: zypixllc@gmail.com
timezone: America/Los_Angeles
baseurl: "/blog"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Brian
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  brian:
    name: Brian
    display_name: Brian 
    avatar: 'assets/images/sal.png'
    email: zypixllc@gmail.com
    description: "Author of blog"
  jay:
    name: Jay
    display_name: Jay
    avatar: 'assets/images/john.png'
    email: zypixllc@gmail.com
    description: "Author of blog"

# Social
# social:
#   instagram: https://www.instagram.com/bootstrapstarter/
#   facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
#   twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives